### ISSUE TITLE
Doesn't begin tracking clipboard until opened once during that session

### ISSUE THREAD

**Issue by mosqueteiro** [atiladefreitas/lazyclip#1]
I am liking the flow of this plugin but one thing does make this a little annoying. Lazyclip doesn't start tracking the clipboard until it has been opened once during that session. So if I start out opening a file with neovim and yank a couple things then I try to open the lazyclip manager it says empty list. Now if I go yank a couple things they start to populate the manager. Ideally Lazyclip would start tracking the clipboard when neovim is started or once Lazyclip has been loaded.

**Comment by atiladefreitas** [comment]
added bug label but in this case was an missing feature. I will commit this fix

**Comment by mosqueteiro** [comment]
~It still isn't initializing on neovim open but~ I tried adding the `event = { 'TextYankPost' }` and it initializes after the first yank. It misses capturing the first yank but gets everything after that. I changed the event to `'VimEnter'` and now it works at startup :partying_face:
